---
output:
  pdf_document: default
  html_document: default
  editor_options: 
    chunk_output_type: console
  chunk_output_type: console
---

# Discussion

Our primary goal for Study 2 was to provide a pseudo-replication of our Study 1 hypothesis, with improved experimental materials intended to reduce confusion. Hypothesis 1 was not supported by the results of our intervention. We recorded the exact opposite effect; our intervention was less effective at increasing support for UHC than our control. Additionally, we directly measured our two proposed mediating relationships through Hypothesis 2. We believed that greater perceived equity would increase support for UHC (H2a). We also believed increased comprehensibility would increase support for UHC (H2b).

Hypothesis 2a was supported by the results of our intervention. The data indicated that perceived equality was a significant mediator for support for UHC. Using the bootstrapping method outlined by Tingley and colleagues (2014), we estimated that perceived equality is a significant mediator on support for UHC not just in our sample, but in the population. Our intervention condition was perceived to have lower equity than our control, which partly explains why our control condition had a greater increase in support for UHC, in opposition to Hypothesis 1. Hypothesis 2b was not supported by the results of our intervention; There was not a significant effect of experimental condition on comprehensibility. Lastly, we intended to determine if objective and subjective numeracy would moderate the effect of intervention condition on support for UHC in Hypothesis 3. Hypothesis 3 was partially supported by the results of our intervention. We saw a significant effect of objective, but not subjective numeracy, on support for UHC. Furthermore, we found a significant interaction between the effect of objective numeracy and our intervention condition. Subjects low in objective numeracy had greater support for UHC in our control condition compared to our intervention condition, in opposition to Hypothesis 1. Yet subjects high in objective numeracy had greater support for UHC in our intervention condition compared to our control condition, in support of Hypothesis 1. This indicates that our initial Hypothesis 1 is valid, but only for subjects with higher objective numeracy.  

In line with previous research, we did find that the majority (69% of our subjects) of our participants found the HBP acceptable (Goold et al., 2000; Danis et al., 2004). We also replicated the positive level of support found by Huebner et al. (2006), but in a non-medical student population. However, we only partially replicated previous work on the effects of active versus passive instruction (Haidet et al., 2004; Michel et al., 2009; Weiger et al., 2019). We found that active learning was more effective, but only for subjects with higher numeracy. Hadiet and colleagues (2004) found that active instruction was effective for mathematically focused content, we believe that this is due to high objective numeracy further improving the effect of active instruction. The large advantage that the more numerate have is exacerbated even further by active instruction using numbers. Addressing the lack of impact for low-numeracy subjects is necessary to bridge the understanding gap created by the high complexity of UHC.

Study 2 provided mixed evidence regarding our mediational hypothesis. Both perceived equality as well as understanding of UHC strongly predicted support for UHC. However, our experimental intervention lowered perceived equality and neither condition influenced comprehensibility. It is plausible that there is partial mediation of perceived equity on support for UHC. However, our intervention did not successfully improve perceptions of equity. This is a repudiation of previous research by Hurst et al., (2018) regarding the HBP framework being perceived as fair. We were able to determine that comprehensibility is a strong predictor for support for UHC, but further research is necessary to determine how best to improve comprehensibility.  

We had no a-priori assumptions regarding the impacts of numeracy. Peters (2020) writes that objective numeracy measures the ability to use knowledge of basic probability and mathematics, as well as to communicate and interpret mathematical information. In comparison, subjective numeracy represents confidence in ability to understand mathematics, and the preference for numbers over words. Plausibly, those who lack objective numeracy, may find it difficult to engage in calculating and trading off options. Alternatively, more numerate individuals could engage more in a numbers-based activity, paying more attention and thus resulting in a larger effect.

In our intervention, the main source of difficulty was ‘agonizing’ over distribution of resources for an ideal health plan. This is intentional, making realistic and difficult choices akin to those for health-care officials is the purpose of the exercise. Additionally, many individuals in our intervention condition expressed support and appreciation for the exercise. This provides further evidence that the HBP based active intervention was indeed successful at improving engagement. However, one consistent category of responses across both conditions expressed belief that the exercise was either politically motivated or had a strong intentional bias in its construction. To address this, we could present a HBP for a UHC in comparison to a set of standard private insurance plans. Additionally, measuring political affiliation could allow us to directly examine the effect of political motivation on support for UHC. 

# Limitations

Study 2 recruited participants from a large midwestern university located in a medium sized midwestern city. This limits the amount of generalization to other populations. The design of Study 2 required familiarity with internet and online survey platform technology, which may make it difficult to adapt to older or less tech-savvy populations. Some subjects indicated in the free-response section that the information presented was biased towards support for UHC and did not paint the whole picture of arguments supporting our current private care system. Therefore, we were unable to derive potential insights comparing to see if positive messaging on private health care would reduce support for UHC.

# Future Directions

The lowest-hanging fruit is a replication of the study, providing evidence of our proposed mediating relationship and moderating effects, on a group that more closely mimics the insurance buying public. This would provide additional external validity, as the primary decision-makers around health insurance are not university students. Another extension for replications of this research would be to developing a structured plan for qualitative analysis such as semantic text analysis, LIWC specifically.

There are several modifications of the experimental materials that would be of interest to examine. One would be determining if different resource availability would have greater or lesser support. If there is no significant difference, that would perhaps provide evidence indicating that the structure of an HBP could have has greater salience in determining approval versus simply the objective healthcare options available.

Another valuable extension would be to measure additional moderating variables. Political orientation and polarization are two variables explicitly referenced in our free response section by participants. We could also design experimental material that explicitly promotes ‘standard’ private health insurance as it exists in the US or compare to negative messaging on ‘standard’ private health care without having positive information about UHC. 

The most valuable extension would be to determine how to increase support for UHC with individuals that have lower objective numeracy. Low objective numeracy is common in the US population. Having an intervention that only works to increase support for UHC in individuals with high-objective numeracy is problematic as we would want to impact the whole of the population. Some considerations could be a simplified version of the exercise, or to clearly indicate the trade-offs using a computer activity that does not explicitly reference numbers or calculation.