---
output:
  pdf_document: default
  html_document: default
---
# Introduction

Healthcare in the United States is a significant financial burden on the average American. Medical expenses are the top contributor to bankruptcy in America, and insurance is unaffordable for many Americans, indicated by the fact that 11.1% of the population is uninsured [@Himmelstein2005; @Roco2014]. An additional 21.3% of Americans are underinsured, defined as unsustainable health spending, with 10% of household income going to health costs[@Schoen2005]. Because healthcare spending is unsustainable for people who are uninsured or underinsured, the majority of this group goes without necessary medical services.

The US government also spends an astronomical amount on health care annually, particularly in comparison to peer nations. In 2016, 17.8% of GDP was spent on healthcare, with other with other peer countries spending between 9.6% to 12.4%. Shockingly, the US also has the lowest life expectancy of these countries, 78.8, compared to an average of 81.7 and ranks poorly in most markers of health outcomes [@Papanicolas2018a]. 

One answer to skyrocketing health costs and ineffective outcomes is Universal Health Care (UHC). UHC directly addresses US concerns regarding cost of healthcare, lack of coverage, and poor health outcomes. Cost of implementation temporarily spikes total healthcare spending but has historically resulted in reduced spending later [@Hsiao2019]. UHC increases healthcare coverage, resulting in lower mortality and better overall health in the population [@Panpiemras2011; @Galvani2017]. While there are clear benefits to UHC in the US, only 28.2% Americans support doing so [@Holahan2019]. Thus, increasing the likelihood of implementation by improving support for UHC is valuable. The goal of this project is to examine the interventions designed to increase support of UHC that directly address common reasons for opposition.

## Inadequacies with our current system

The purpose of health care is to improve the well-being of those treated. However, 61% of all debt in America originates from medical costs, with the average American owing \$9,374 [@Austin2014 ; @Schoen2005]. The American health system often worsens the well-being of those treated instead; Medical debtors are 42% more likely to suffer from a lapse in medical coverage [@Himmelstein2005]. This is particularly relevant in the US as some of our most disadvantaged minorities simultaneously suffer from low rates of insurance compared to Whites (11.7% for Whites, 20.8% for Blacks, 30.7% for Hispanics) [@Shen2016]. Medical debt is partly due to extreme cost differences in care; The US pays approximately twice as much as peer countries for medical procedures and pharmaceuticals [@Anderson2003; @Papanicolas2018a; @Tikkanen2020]. This is compounded by unwillingness to ration care and administrative complexity, pushing cost higher with low value outcomes [@Reinhardt2004]. The U.S. system of multiple insurers leads to under-investment in preventative care and in medical infrastructure that generates long term value. This is since insurers share the benefits from the cost of implementation with their competitors. The US health system has high waste due to the lack of centralized payment and distribution as well [@Shrank2019]. Estimates of waste are nearly $1 trillion, approximately 25% of total health spending. Over 40% of this waste is due to administrative complexity and inflated pricing. Medical care is plainly unaffordable in the United States for many.

Health outcomes in the US are notoriously poor. Life expectancy in the US has not improved since 2014, even as the per capita cost of healthcare has risen from \$9,466 to $11,582 [@Murphy2014; @Kochanek2020]. This is distressing when we consider that up to 50% the care provided is not evidence based [@Manchikanti2010]. Low quality and ineffective pharmaceuticals are distributed more quickly through the US health system compared to peer countries with UHC due to demands for rapid adoption of new treatments, without necessarily proving their long-term efficacy [@Kyle2017]. US healthcare is ranked as low as 15th out of 25 major industrialized countries, due to inflated costs, waste, fraud, and the poorest aggregate utilization of physician visits and hospital days [@Koopman2000; @Anderson2003]. The US also falls behind other peer countries on almost every health outcome metric [@Tikkanen2020]. The US has the highest suicide rate with 13.9 per 100,000 versus an average of 11.5. The US also suffers from the highest chronic disease burden (28% of population versus an average of 17.5%) and rate of obesity (40% versus an average of 21%) by far. Lastly, people in the US have the highest rates of hospitalizations and deaths from preventable causes (approximately 50% greater hospitalizations, and 70% greater deaths, than peer-country averages). While the US spends the most in both percentage of GDP and total expenditure on healthcare by a significant margin, our health outcomes are uniformly worse than peer nations.

## Benefits of Universal Health Care

A resolution adopted by the UN General Assembly states that UHC is “access to key promotive, preventive, curative, and rehabilitative health interventions for all at an affordable cost” [@Assembly1991]. The most obvious benefit of UHC is that it leads to improvement in coverage. In Thailand and Taiwan, within one year of implementation of UHC, insurance coverage surged from less than 57% to over 97% [@Panpiemras2011; @Hsiao2019]. This improvement in coverage is vital. In the US, the uninsured and underinsured are between 25-40% more likely to die, leading to 44,000 deaths per year, rivalling the impact (42,000 deaths) of kidney disease [@Wilper2009]. Neonates are especially at risk, with lack of insurance increasing the risk of death by 260%, more than being born with congenial malformation [@Morriss2013]. In general, by improving coverage, population health improves. 

Furthermore, UHC can improve health outcomes through avenues other than increased coverage. A UHC system allows for centralization of control and information. During both the 2003 SARS epidemic and the 2009 H1N1 outbreak in Taiwan, automatic reporting and contact tracing integrating the travel and healthcare systems allowed for simple and effective contact tracing [@Hsiao2019]. Greater proportions of public health spending versus private health spending have also been shown to enhance overall health in 17 peer countries [@Kim2013].  Each percentage increase in public expenditure reduces infant mortality by 0.077% and increases life expectancy by 0.026 years. UHC is a functional way to increase the proportion of public health spending.

In addition to improving coverage, quality of healthcare, and health outcomes, UHC is also effective at reducing waste and costs in healthcare. A 30-year examination of peer countries that implemented a single payer system (controlling for health status, demographics, level of preventative medicine, and political factors) showed a difference in cost of .75% of GDP, estimated at 150$ billion per year in the US [@Bichay2020]. Half of the saved cost is due to reduced cost of medical goods and administrative spending (0.37% GDP) and most of the rest is due to improved health outcomes (0.2% GDP). Current waste in the US system due to administrative costs could be reduced by 33-53% with the adoption of UHC [@Scheinker2021]. Moreover, centralization due to UHC allows for savings from improved information aggregation and analysis. The Taiwanese National Healthcare Insurance Administration has used statistical modeling to identify outlier health providers, leading to an 8% reduction in expenditures within their first two years of operation by controlling fraud and abuse [@Hsiao2019]. Additionally, while the US uses 10% fewer drugs per capita than other peer countries, prices are 50% higher for equivalent drugs [@Manchikanti2009]. An extreme example can be found when looking at recent price spikes in the US for toxoplasmosis drugs (a 5,500% increase) and EpiPens (a 791% increase), which did not occur in Europe or Canada. Countries implementing single-payer systems have lower average pharmaceutical costs, due to lower pharmaceutical prices and prioritization of effective generic alternatives to expensive brand-name drugs [@Morgan2017]. By creating a functional single buyer market, UHC is effective at limiting aggregate costs across the board in both healthcare goods and technologies [@Hussey2003]. 

## Opposition and Support to Universal Health Care

One source of opposition to UHC in the United States is due to difficulties understanding UHC. In Americans that oppose UHC, approximately half were unable to understand the structure of the Affordable Care Act (ACA) or its component pieces [@Nissan2011; @Lillie-Blanton2000]. Furthermore, misinformation regarding UHC is extremely common, as over 60% of Americans cited television as their primary source of information about the ACA (a step towards UHC). Plainly untrue statements were propagated, such as calling the ACA “socialism” or “a seizure of one sixth of the economy” [@Skidmore2012]. Television advertisements originating from Republican candidates in 2012 and 2014 painted an immensely negative picture of UHC, which was possible in part due to lack of information [@Dalen2015]. 

A study by Huebner and colleagues -@Huebner2006 found that U.S. medical students struggled to come to consensus on terms related to UHC such as “fee for service”, “single-payer”, and “universal health care”. This illustrates difficulty in understanding UHC. The authors also note that they were not able to define ‘complex policy terms’ in the questionnaire, indicating a need to explain UHC in a simpler fashion. Academic understanding and analysis of UHC has also been harmed due to a lack of a shared etymology [@Hsiao2019].  Additionally, belief that UHC would make the healthcare more comprehensible is strongly correlated with willingness to support UHC [@Holahan2019]. 89.4% of those that support UHC believe that UHC would make health care simpler and easier, where only 50% of those that oppose UHC believe the same. 

Knoll and colleagues -@Knoll2015 have found that increased saliency and belief in ‘Nativism’, defined as the perception that foreign influence despoils traditional American heritage, predicts opposition to health care reform. Surprisingly, this holds true for both Republicans and Democrats.  Additionally, this was after controlling for partisanship, ideology, and racial resentment, which all had independent significant effects on support for health care reform. The total effect was that strongly nativist beliefs lead to a 35.5% reduction in belief that health reform was at least favorable or ambivalent, compared to those with strongly non-nativist beliefs. 

Another common source for opposition to UHC in the US is the perception that UHC is inequitable. Belief that UHC would lead to equitable coverage is strongly correlated with support for UHC. 91% of those that support UHC believe that equitable coverage is important, while only 45% of those that oppose UHC believe the same [@Holahan2019]. Furthermore, when Shen and colleagues -@Shen2016 examined the impact of racism on support for UHC, they found that perceived inequity was the mechanism through which racism impacted support for UHC. The authors hypothesized that Whites opposed government programs designed to eliminate racial inequity because it constituted unjust government assistance. While UHC is not designed to specifically benefit Blacks, individuals harboring racist beliefs may assume that is the case. Crucially, whether the individual purported to benefit from UHC was a ‘free-rider’ (inequitably benefitting from UHC) was what predicted opposition to UHC. This was unrelated to race. 

## Previous US Attempts towards UHC

There have been several attempts to implement UHC in the United States at the state level (e.g., California, Washington, Florida, etc.); however, none have been successful to date. In 2011, the local legislature in the state of Vermont enacted a bill guaranteeing UHC for all Vermont residents [@Agency2017]. This bill, known as “Green Mountain Care”, was seen as both a tool to improve health outcomes in Vermont and a way to reduce medical costs and strengthen the economy. Three different independent organizations projected this to be the case, with a consensus that immediate healthcare costs for Vermont would be lowered by 8-12% and another 12-14% over the next 10 years [@Hsiao2011; @McDonough2015]. Combined with the fact that cost increases were estimated to be only 9.4% for employers and 3.1% for individuals, total savings across the system were estimated to be $378 million over 5 years. Difficulties arose in implementation however, due to a combination of reduced federal revenue and increased scope of coverage to nonresidents working in Vermont. The plan was eventually abandoned in 2014, due to proportionally larger taxes on business and difficulty in communicating the benefits arising from elimination of current premium costs [@Fox2015]. The public was hyper-aware of the tax raises necessary to implement the program, but Vermonters did not receive clear messaging on the net savings that would result from replacing current premiums with a tax raise. 

Oregon is another state where UHC expansion has been debated and examined. The Oregon Medicaid lottery in 2008 was the first time in the US where a randomized controlled study on UHC was possible. Data from roughly 6,000 adults who were selected to apply for Medicaid, and 6,000 who were not, allowed for objective evaluation [@Baicker2013]. Researchers found no significant improvements over a two-year period in direct measurements of health, such as blood pressure, cholesterol, blood sugar, tobacco use, or obesity [@James2015]. However, significant benefits arose in the form of greater management for continuing conditions, lower depression, and most significantly, an almost complete elimination of catastrophic out of pocket medical expenses, leading to lower medical debt. The primary concern from critics were  concerns that many objective physical health outcomes saw no improvement, and that while self-reported health did show significant improvement, it was less important given the inherent noise in self-reported data. Given these concerns, UHC was seen as politically infeasible, even though 62% of Oregon voters would “definitely” or “probably” support a UHC plan that would double or triple state taxes [@Rosenberg2020]. 

## Health Benefits Packages

Interventions specifically attempting to directly improve support for UHC have not previously been examined in the literature. A potential intervention that would directly address US concerns towards UHC would be to present UHC within the framework of a Health benefits package (HBP).  A HBP is defined by three factors [@Glassman2016]. First, HBPs are a comprehensive portfolio of services (e.g., dental, mental health, pharmaceuticals) as compared to programs that only cover a single service (e.g., GoodRx and pharmaceuticals). This allows assessment of cost effectiveness by directly comparing different services to one another. Second, HBPs are designed and priced using actuarially informed estimates of supply and demand. Third, HBPs constrain the services made available through the public health system, but by doing so, guarantee that at least certain services will be made available. 

In the American system of health care, many experts agree that efficiency and quality of care are unlikely to be improved without an HBP like system, combining a well-defined framework with the legal specificity necessary for regulation [@Chalkidou2014]. As HBPs create explicit entitlements for patients, they reduce confusion as to what is being offered. Furthermore, HBPs help ensure fairness and equity by preventing discretionary variation in access to care that would otherwise be largely determined by clinical professionals. In countries with UHC without an HBP linked to cost, there are significant gaps in coverage,  implicit rationing, and consequently lower quality healthcare outcomes (e.g., higher infant mortality, greater spread of communicable disease). For example, Uganda has intended to guarantee UHC to all citizens since 1999 [@Odokonyero2017]. However, by 2017, only 52% of their poorest, and 69% of their wealthiest citizens had coverage. Inefficient concentration of resources in urban areas lead to implicit rationing of comprehensive coverage for most Ugandans, living in rural areas without easy access to transportation. Another parallel can be found in Ghana’s National Health Insurance Scheme [@Agyepong2016]. Implemented in 2003 to provide UHC, by 2016 only 40% of the population had coverage. Critically, enrollment stagnated due to citizen unhappiness with the system; Concerns included frequent stock-outs of pharmaceuticals, unequal enforcement of regulations, and the perception that certain minority groups benefited inequitably. Clear evidence exists that lacking an HBP in several countries has resulted in an ineffective attempt at achieving UHC, both in citizen perception, and wholeness of coverage. 

Conversely, countries that have UHC with an HBP are perceived as well functioning. 78% of Swiss citizens surveyed perceived their HBP based system as one that is fair for the ill, due to a combination of appropriate levels of coverage, equal protection to all Swiss citizens, and increased knowledge about the health system [@Hurst2018]. As another example, when a HBP was used to examine different configurations of Medicare benefits in the U.S., 83% of studied enrollees agreed that the consensus plan provided was fair [@Danis2004]. Furthermore, 66% agreed strongly, and a further 30% agreed somewhat that the HBP was easy to understand. Most importantly, 86% of participants believed that the presented HBP was one they were satisfied with. Presenting otherwise complex trade-offs of health benefits in a simple, easy to understand fashion was extremely beneficial.

Emphasizing the necessary nature of tradeoffs or compromises in medical care and doing so in a clear and easy to understand way is vital. Developed by Goold and colleagues -@Goold2005, the Choosing Healthplans All Together intervention explains HBPs clearly by directly addressing these concerns. The central tenet of the CHAT exercise is for participants to construct their own HBP by allocating a limited set of resources to benefit types (e.g., dental, fertility treatments, long-term care) and choosing scope of coverage (e.g., generics instead of name-brand drugs, amount of copayments, etc.). The purpose of the exercise was initially to help explain how trade-offs in medicine are necessary, as well as to determine what the subjects prioritize in healthcare given limited resources. The final chosen plan is clear and explicit in types of care and intensity of treatment available, neatly addressing consumer confusion.

The CHAT exercise has been a success, with over 95% of participants finding the task easy to do across several different implementations of the exercise [@Danis2002; @Danis2004; @Goold2005]. CHAT has also been adapted twice to explore trade-offs in specific government funded health plans. First, Danis and colleagues (2004) used the CHAT framework to illustrate the financial constraints of government funded Medicare and to assist Medicare enrollees in developing a consensus on what services they want to prioritize. Participants first individually went through the CHAT exercise, then were grouped with approximately 12 participants each; These groups engaged in CHAT, with options being decided by simple majority votes, to reach a consensus HBP. While 41% of participants felt that the HBP designed as a group was different than what they would have chosen for themselves, 86% were still satisfied with the HBP they developed. The second adaptation, by Hurst and colleagues -@Hurst2018, was used to examine how Swiss citizens would prioritize types of care in the already extant Swiss HBP based UHC system. The participants had no trouble using the exercise to improve their understanding of the Swiss HBP, were easily able to make trade-offs and set priorities, and found that they were able to reach a strong consensus. This was exceptionally valuable due to the diversity of opinions observed in the study. 

It is important to note that the CHAT exercise is particularly valuable because it is a hands-on exercise as compared to a simple informational intervention. Work by Wegier and colleagues -@Wegier2019 found that a simulated experience led to more accurate understanding of information as compared to simply being given explicitly described statistics. Furthermore, active instruction is particularly time efficient and engaging when learning complex, numeracy-focused material [@Haidet2004].  Active instruction is also particularly effective at improving subject-specific knowledge gains [@Michel2009]. These characteristics are an ideal match for the material presented in an HBP. Thus, it is reasonable to believe that active instruction will be more effective than a simple ‘fact sheet’ for an HBP that would otherwise be presented to the public.

## The Present Research

The goal of our two studies is to determine whether exposure to UHC through the framework of an HBP can improve support for UHC. Based on previous research, we know that UHC is likely to benefit the US if implemented, and that HBP directly addresses some of the primary reasons that are foundational to opposition of UHC. Regardless, no direct research has been done previously on the effects of HBP on UHC.